spring.application.name=ClassFlow

spring.datasource.url=jdbc:postgresql://db.ziergckfzkpexnusopcv.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=classflow6537

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect